package Interface.Configuracoes;

import Entidades.*;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.EOFException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julio Cesar
 */
public class ConfigParametros extends JFrame {

    /**
     * Creates new form NewJFrame
     */
    public ConfigParametros() {
        try {
            initComponents();
        Internacionalização.initComponet();
        centralizarComponente();
        setDadosNewConfig();
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonSelecionarCor = new javax.swing.JButton();
        jButtonSelectCaminho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parametros");

        jTable.setBackground(jPanel1.getBackground());
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Parametro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonSelecionarCor.setText("Selecionar cor");
        jButtonSelecionarCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarCorActionPerformed(evt);
            }
        });

        jButtonSelectCaminho.setText("Selecionar caminho");
        jButtonSelectCaminho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectCaminhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSelecionarCor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSelectCaminho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSelecionarCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSelectCaminho)
                .addGap(352, 352, 352))
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        salvar(System.getProperty("user.dir"), "Inter.bin");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonSelecionarCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarCorActionPerformed
        // TODO add your handling code here:
        Color color = getBackground();
        color = JColorChooser.showDialog(
                ConfigParametros.this, "Escolher a color", color );
        jTable.setValueAt(color, jTable.getSelectedRow(),2);
        
    }//GEN-LAST:event_jButtonSelecionarCorActionPerformed

    private void jButtonSelectCaminhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectCaminhoActionPerformed
        // TODO add your handling code here:
         JFileChooser fc = new JFileChooser();
         fc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
       // BufferedImage imagem ;
        //  String user;
        int id = 0;
        int valido = fc.showOpenDialog(jPanel1);
        if (valido == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            jTable.setValueAt(file.toString(), jTable.getSelectedRow(),2);
        }
    }//GEN-LAST:event_jButtonSelectCaminhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigParametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigParametros().setVisible(true);
            }
        });
    }

    

    private void add(String s, Object o) {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        Object[] linha = {s, o.getClass(), o};
        model.addRow(linha);

    }

    private void setDadosNewConfig() {

        add("Cor atençao", Internacionalização.getCorAtencao());
        add("Cor nome da empresa", Internacionalização.getCorNomeEmpresa());
        add("Cor padrão", Internacionalização.getCorPadrao());
        add("Id inspçao normal", Internacionalização.getIdInspNoraml());
        add("Id manutençao geral", Internacionalização.getIdManuGeral());
        add("Id inspeçao sem ocorencias", Internacionalização.getIdSemOcorencia());
        add("Imagen de fundo", Internacionalização.getLinkImagenFundo());
        add("Loca salvar midia", Internacionalização.getLinkSalvarMidia());
        add("Nome da empresa", Internacionalização.getNomeEmpresa());
        add("id tipo equipamento", Internacionalização.getTipoEquipamento());
        add("id tipo setor", Internacionalização.getTipoSetor());
        add("Formato data brasil", Internacionalização.getFormatoDataBrasil());
        add("Formato data USA", Internacionalização.getFormatoDataUSA());
        add("Link icone Equipamento", Internacionalização.getIconeEquipamento());
        add("Link icone Equipamento atençao", Internacionalização.getIconeEquipamentoRed());
        add("Link icone setor", Internacionalização.getIconeSetor());
        add("Link icone setor atençao", Internacionalização.getIconeSetorRed());

    }

    private ConfigInternacionalização getDadosNewConfig() {

        int i = 0;
        ConfigInternacionalização config = new ConfigInternacionalização();
        config.setCorAtencao((Color)jTable.getValueAt(i, 2));
        i++;
        config.setCorNomeEmpresa((Color)jTable.getValueAt(i, 2));
        i++;
        config.setCorPadrao((Color)jTable.getValueAt(i, 2));
        i++;
        config.setIdInspNoraml((Integer) jTable.getValueAt(i, 2));
        i++;
        config.setIdManuGeral((Integer) jTable.getValueAt(i, 2));
        i++;
        config.setIdSemOcorencia((Integer) jTable.getValueAt(i, 2));
        i++;
        config.setLinkImagenFundo((String) jTable.getValueAt(i, 2));
        i++;
        config.setLinkSalvarMidia((String) jTable.getValueAt(i, 2));
        i++;
        config.setNomeEmpresa((String) jTable.getValueAt(i, 2));
        i++;
        config.setTipoEquipamento((Integer) jTable.getValueAt(i, 2));
        i++;
        config.setTipoSetor((Integer) jTable.getValueAt(i, 2));
        i++;
        config.setFormatoDataBrasil((String) jTable.getValueAt(i, 2));
        i++;
        config.setFormatoDataUSA((String) jTable.getValueAt(i, 2));
        i++;
        config.setIconeEquipamento((String) jTable.getValueAt(i, 2));
        i++;
        config.setIconeEquipamentoRed((String) jTable.getValueAt(i, 2));
        i++;
        config.setIconeSetor((String) jTable.getValueAt(i, 2));
        i++;
        config.setIconeSetorRed((String) jTable.getValueAt(i, 2));

        return config;

    }

    public void salvar(String path, String nomeArquivo) {
        try {
            getDadosNewConfig();
            ConfigInternacionalização configBanco = getDadosNewConfig();
            Path novo = Paths.get(path);
            Files.createDirectories(novo);
            try (ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream(path + "\\" + nomeArquivo))) {
                output.writeObject(configBanco);
                if (output != null) {
                    output.close();
                    JOptionPane.showMessageDialog(null, "Salvo com sucesso", "Arquivo salvo com sucesso em" + path, JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao abrir arquivo \n" + path + "\n" + ex.toString(), "Erro ao abrir arquivo\n" + path, JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao abrir arquivo \n" + path, "Erro ao abrir arquivo\n" + path + "\n" + ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }

    }

    public static Internacionalização leitor(String path, String nomeArquivo) {
        Internacionalização config = null;

        ObjectInputStream input = null;
        try {
            input = new ObjectInputStream(new FileInputStream(path + "/" + nomeArquivo));

            while (true) {
                config = (Internacionalização) input.readObject();

            }
        } catch (EOFException endOfFileException) {
            return config;
        } catch (ClassNotFoundException classNotFoundException) {
            JOptionPane.showMessageDialog(null, "Unable to create object.");
        } catch (IOException ex) {

            JOptionPane.showMessageDialog(null, "Erro ao abrir arquivo \n" + path + "\n" + ex.getMessage());
        }
        try {
            input.close();
        } catch (IOException ex) {
            Logger.getLogger(ConfigurarBanco.class.getName()).log(Level.SEVERE, null, ex);
        }
        return config;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSelecionarCor;
    private javax.swing.JButton jButtonSelectCaminho;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
